name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches:
      - main
      - team1-aashish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
        env:
          REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync ./frontend/build s3://team1-cicdws-bucket --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E3HRJ1SDFFELJY --paths "/*"

  cypress_e2e:
    needs: deploy
    runs-on: ubuntu-latest

    env:
      CYPRESS_BASE_URL: ${{ secrets.FRONTEND_DEPLOY_URL }}
      CYPRESS_API_URL: ${{ secrets.BACKEND_API_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./e2e-tests
        run: npm install

      - name: Run Cypress E2E tests
        working-directory: ./e2e-tests
        run: npx cypress run
